# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  os = "centos/7"
  net_ip = "192.168.10"
  master_name = "master-01"

  config.vm.define :"#{master_name}", primary: true do |master_config|
    master_config.vm.provider "virtualbox" do |vb|
#        vb.memory = "2048"
        vb.memory = "1024"
        vb.cpus = 1
        vb.name = "#{master_name}"
    end
      master_config.vm.box = "#{os}"
      master_config.vm.host_name = 'master-01.local'
      master_config.vm.network "private_network", ip: "#{net_ip}.10"
      master_config.vm.synced_folder "saltstack/salt/", "/srv/salt"
      master_config.vm.synced_folder "saltstack/pillar/", "/srv/pillar"

      master_config.vm.provision :salt do |salt|
        salt.master_config = "saltstack/etc/master-01"
        salt.master_key = "saltstack/keys/master_minion.pem"
        salt.master_pub = "saltstack/keys/master_minion.pub"
        salt.minion_key = "saltstack/keys/master_minion.pem"
        salt.minion_pub = "saltstack/keys/master_minion.pub"
        salt.seed_master = {
                            "minion-01" => "saltstack/keys/minion-01.pub",
                            # "minion-02" => "saltstack/keys/minion-02.pub",
                            # "minion-03" => "saltstack/keys/minion-03.pub",
                           }

        salt.install_type = "stable"
        salt.install_master = true
        salt.no_minion = false
        salt.verbose = true
        salt.colorize = true
        salt.bootstrap_options = "-P -c /tmp"
      end
    end


    [
      ["minion-01",    "#{net_ip}.11",    "512",    "centos/7" ],
      # ["minion-02",    "#{net_ip}.12",    "512",    "centos/7" ],
      # ["minion-03",    "#{net_ip}.13",    "512",    "centos/7"],
    ].each do |vmname,ip,mem,os|
      config.vm.define "#{vmname}" do |minion_config|
        minion_config.vm.provider "virtualbox" do |vb|
            vb.memory = "#{mem}"
            vb.cpus = 1
            vb.name = "#{vmname}"
        end
        minion_config.vm.box = "#{os}"
        minion_config.vm.hostname = "#{vmname}"
        minion_config.vm.network "private_network", ip: "#{ip}"

        minion_config.vm.provision :salt do |salt|
          salt.minion_config = "saltstack/etc/#{vmname}"
          salt.minion_key = "saltstack/keys/#{vmname}.pem"
          salt.minion_pub = "saltstack/keys/#{vmname}.pub"
          salt.install_type = "stable"
          salt.verbose = true
          salt.colorize = true
          salt.bootstrap_options = "-P -c /tmp"
        end
      end
    end
  end
